language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get install -y libgtest-dev
  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: cmake --build .

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libgtest-dev valgrind cmake
 - sudo wget https://github.com/google/googletest/archive/release-1.8.1.tar.gz
 - sudo tar xf release-1.8.1.tar.gz
 - cd googletest-release-1.8.1
 - sudo cmake -DBUILD_SHARED_LIBS=ON .
 - sudo make
 - sudo cp -a include/gtest /usr/include
- sudo cp -a libgtest_main.so libgtest.so /usr/lib/